---
layout: cv
title: Taylor Everett's Resume
---
# Taylor Everett
Student and Merchandising Assistant 

<div id="webaddress">
<a href="tayloreverett72@gmail.com">tayloreverett72@gmail.com</a>



## Currently

Working and Studying Business Analytics Full Time

### Specialized in

Power BI, Excel, MySQL, Python


### Research interests

Furthering my knowledge in financial analytics as well as EDI and PowerBI 



## Education

`2021-2025`
__BYU-I.__



## Occupation

`2022-Current`
__Merchandising Assistant__, Country Supplier

-	Ordered a wide variety of product to 55 stores. 
-	Mid States SPOC for Country Supplier and Oversaw all communication between the two companies  
-	Was involved in  the Implementation of a new EDI process for stores to recieve product into inventory
-	Analyze large data to find valuable actionable insights for the replenishment team
-   Created useful reporting workbooks that auto update upon opening  


`2022-2023`
__Back-Up Receiver__, C-A-L Ranch
-	Completed Multiple tasks such as checking inventory into our system as well as sending out packages to other stores 
-	Analyzed all my work was done to perfection or near perfection 
-	Ensured inventory numbers stay accurate that way our reorder points are correct 
-	Train others in the position to the same level that I am at that way the work was done the proper way 
-	Ensuring freight is moving out of the back room in a timely matter 
-	Collaborated with many individuals at the corporate level to solve problems that come up 


`2020-2021`
__Laborer__, Arylett

-	Completed Multiple tasks from manufacturing to shipping and packaging  
-	Learned to guide and teach people about the job as they were hired. I went from the new slow guy to one of the fastest workers in a matter of weeks   
-	Oversaw from start to finish over many products throughout a shift 
-	Completed tasks 8 hours a day at a constant rate of speed  
<!-- ### Footer

Last updated: December 2024 -->